# Generated by Django 3.1.3 on 2020-11-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201109_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'абвг', 'verbose_name_plural': 'абвг'},
        ),
    ]
